title: Tyler's Project Repository
author: Tyler Hanyin Wang
  name: 
  email: hello@tylerhanyinwang.com

description: Studying at EWU for Bachelor of Science in CS, specifically learning Java, SQL, and C. Self-taught in python, and C#.

theme: minima

header_pages:
  - homebrew.md

minima:
  skin: dark