theme: jekyll-theme-slate
title: Tyler Hanyin Wang
description: Coder, currently studying CS. Self-taught in python, C# for Unity. Taking courses at EWU for Java, SQL, and C.

Worked on a number of things, driven by interest in automation and game design.